name: Build

on:
  pull_request:
    branches:
      - main

env:
  OPENCV_VERSION: "4.9.0"

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      OPENCV_LINK_LIBS: "opencv_world490"
      OPENCV_LINK_PATHS: "C:/tools/opencv/build/x64/vc16/lib,C:/tools/opencv/build/x64/vc15/lib"
      OPENCV_INCLUDE_PATHS: "C:/tools/opencv/build/include"
    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenCV and LLVM
        run: choco install opencv llvm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run check on Windows
        run: cargo check --features=cli --bins

  build-macos:
    runs-on: macos-latest
    env:
      DYLD_FALLBACK_LIBRARY_PATH: "$(xcode-select --print-path)/usr/lib/"
    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenCV and LLVM
        run: brew install opencv llvm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run check on macOS
        run: cargo check --features=cli,metal --bins

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenCV for Ubuntu
        run: sudo apt install -y libopencv-dev clang libclang-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run check on Ubuntu
        run: cargo check --features=cli --bins

      - name: Run fmt check
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --features=cli --bins

      - name: Run unit tests
        run: cargo test --features=cli --bins

      - name: Test run surya
        run: cargo run --features=cli --bin surya -- --help
